"""The SessionStart arm hook: a fresh clone's gap between "rules visible" and "gates armed".

Git never clones hooks, so a clone of a governed repo enforces nothing at commit time
until `chock sync` runs. The committed settings.json runs `.chock/bin/claude_code.py`
(agentseam's bundle plus chock's own handler, see `gate/runtime_bundle.py`) when a Claude
Code session opens; these tests pin the two halves -- the installer's committed-file
discipline (shared with pretooluse_install) and the handler's arm-or-instruct behaviour.
"""

from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

from chock.gate import runtime_bundle
from chock.hooks.pretooluse_install import INTERPRETER_PLACEHOLDER
from chock.hooks.sessionstart_install import install_sessionstart_hook

FRAMEWORK_ROOT = Path(__file__).resolve().parents[1]

SESSION_START_PAYLOAD = json.dumps(
    {
        "hook_event_name": "SessionStart",
        "session_id": "s",
        "transcript_path": "/t",
        "permission_mode": "default",
    }
)


def _rendered_runtime(tmp_path: Path) -> Path:
    path = tmp_path / "claude_code.py"
    path.write_text(runtime_bundle.render("claude_code"), encoding="utf-8")
    return path


def _bare_repo() -> Path:
    repo = Path(tempfile.mkdtemp()) / "r"
    (repo / ".chock").mkdir(parents=True)
    return repo


def _settings(repo: Path) -> dict:
    return json.loads((repo / ".claude" / "settings.json").read_text(encoding="utf-8"))


def _entry_command(settings: dict) -> str:
    return settings["hooks"]["SessionStart"][-1]["hooks"][0]["command"]


def test_install_bakes_interpreter_and_vendors_runtime() -> None:
    repo = _bare_repo()
    assert install_sessionstart_hook(repo) is True
    command = _entry_command(_settings(repo))
    assert INTERPRETER_PLACEHOLDER not in command
    assert sys.executable in command
    vendored = repo / ".chock" / "bin" / "claude_code.py"
    assert vendored.read_text(encoding="utf-8") == runtime_bundle.render("claude_code"), (
        "vendored copy must match the render exactly"
    )


def test_reinstall_is_a_no_op() -> None:
    repo = _bare_repo()
    install_sessionstart_hook(repo)
    before = (repo / ".claude" / "settings.json").read_bytes()
    assert install_sessionstart_hook(repo) is False
    assert (repo / ".claude" / "settings.json").read_bytes() == before


def test_adopter_sessionstart_entries_survive() -> None:
    repo = _bare_repo()
    settings_path = repo / ".claude" / "settings.json"
    settings_path.parent.mkdir(parents=True)
    theirs = {"hooks": [{"type": "command", "command": "echo hello"}]}
    settings_path.write_text(json.dumps({"hooks": {"SessionStart": [theirs]}}), encoding="utf-8")
    install_sessionstart_hook(repo)
    entries = _settings(repo)["hooks"]["SessionStart"]
    assert entries[0] == theirs, "the adopter's own entry must survive, first"
    assert len(entries) == 2


def test_committed_entry_from_another_machine_is_kept_byte_for_byte() -> None:
    # settings.json may be committed; a sync on a second machine must not rewrite an
    # equivalent entry with its own interpreter path (diff churn, leaked local path).
    repo = _bare_repo()
    install_sessionstart_hook(repo)
    settings_path = repo / ".claude" / "settings.json"
    settings = _settings(repo)
    hook = settings["hooks"]["SessionStart"][0]["hooks"][0]
    hook["command"] = '"/usr/bin/python3.12"' + hook["command"][hook["command"].index(' "') :]
    settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
    before = settings_path.read_text(encoding="utf-8")
    assert install_sessionstart_hook(repo) is False
    assert settings_path.read_text(encoding="utf-8") == before


def _load_runtime(path: Path):
    spec = importlib.util.spec_from_file_location("chock_claude_code_runtime", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _run_runtime(path: Path, cwd: Path, extra_env: dict[str, str] | None = None) -> subprocess.CompletedProcess:
    env = {**os.environ, "CLAUDE_PROJECT_DIR": str(cwd), **(extra_env or {})}
    return subprocess.run(
        [sys.executable, str(path)], cwd=cwd, env=env, input=SESSION_START_PAYLOAD, capture_output=True, text=True
    )


def test_adapter_is_silent_outside_a_chock_repo(tmp_path: Path) -> None:
    runtime = _rendered_runtime(tmp_path)
    proc = _run_runtime(runtime, tmp_path)
    assert proc.returncode == 0
    assert proc.stdout.strip() == ""


def test_adapter_is_silent_when_already_armed(tmp_path: Path) -> None:
    runtime = _rendered_runtime(tmp_path)
    repo = tmp_path / "r"
    (repo / ".chock").mkdir(parents=True)
    subprocess.run(["git", "init", "-q", "."], cwd=repo, check=True)
    hooks = repo / ".git" / "hooks"
    hooks.mkdir(parents=True, exist_ok=True)
    (hooks / "pre-commit").write_text("#!/bin/sh\n# Generated by Chock\n", encoding="utf-8")
    proc = _run_runtime(runtime, repo)
    assert proc.returncode == 0
    assert proc.stdout.strip() == ""


def test_adapter_instructs_when_chock_is_not_importable(tmp_path: Path, monkeypatch, capsys) -> None:
    repo = tmp_path / "r"
    (repo / ".chock").mkdir(parents=True)
    subprocess.run(["git", "init", "-q", "."], cwd=repo, check=True)
    runtime = _load_runtime(_rendered_runtime(tmp_path))
    monkeypatch.setenv("CLAUDE_PROJECT_DIR", str(repo))
    monkeypatch.setattr(runtime, "_chock_importable", lambda: False)
    import io

    out = io.StringIO()
    code = runtime.main(stdin=io.StringIO(SESSION_START_PAYLOAD), stdout=out, exit=False)
    assert code == 0, "an unarmed clone degrades to advice, never a failed session"
    decision = json.loads(out.getvalue())
    context = decision["hookSpecificOutput"]["additionalContext"]
    assert "chock sync --repo ." in context
    assert "NOT installed" in context


def test_adapter_arms_a_fresh_clone_end_to_end(tmp_path: Path) -> None:
    # The real journey: an initialised repo whose .git/hooks were never cloned.
    runtime = _rendered_runtime(tmp_path)
    repo = Path(tempfile.mkdtemp()) / "r"
    repo.mkdir()
    env = {"PYTHONPATH": str(FRAMEWORK_ROOT / "src")}
    subprocess.run(["git", "init", "-q", "."], cwd=repo, check=True)
    subprocess.run(
        [sys.executable, "-m", "chock.cli", "init", "."],
        cwd=repo,
        capture_output=True,
        env={**os.environ, **env},
    )
    pre_commit = repo / ".git" / "hooks" / "pre-commit"
    if pre_commit.exists():
        pre_commit.unlink()  # what a clone looks like: repo content present, hooks absent

    proc = _run_runtime(runtime, repo, extra_env=env)
    assert proc.returncode == 0
    assert "armed them now" in proc.stdout, proc.stdout + proc.stderr
    assert pre_commit.exists(), "the adapter must reinstall the pre-commit dispatcher"
