"""AMB-2: rule-conflict detection over the compiled ambient surface (.agents/policies/INDEX.md)."""

from __future__ import annotations

import subprocess
import urllib.request
from pathlib import Path

import pytest
import yaml

from chock.index.builder import build_entries
from chock.index.render import render_index
from chock.validation import ambient_parser, checks_conflicts
from chock.validation.checks_conflicts import check_ambient_conflicts
from chock.validation.checks_conflicts import main as conflicts_main
from chock.validation.report import Report

_HEADER = "<!-- GENERATED by `chock sync` -- do not edit -->\n\n# .agents/policies/INDEX.md\n\n"


def _index(rules_section: str) -> str:
    return _HEADER + "## Rules — always apply\n\n" + rules_section


def _write_index(root: Path, text: str) -> Path:
    path = root / ".agents" / "policies" / "INDEX.md"
    path.parent.mkdir(parents=True)
    path.write_text(text, encoding="utf-8")
    return path


def _run(root: Path) -> Report:
    report = Report()
    check_ambient_conflicts(root, report)
    return report


def _line_of(text: str, needle: str) -> int:
    for i, line in enumerate(text.splitlines(), start=1):
        if needle in line:
            return i
    raise AssertionError(f"{needle!r} not found")


def test_two_policies_disagreeing_produce_an_error_naming_both_sides(tmp_path: Path) -> None:
    text = _index("- **policy-a**: never(dead_code): delete\n- **policy-b**: prefer(dead_code): keep\n")
    _write_index(tmp_path, text)

    report = _run(tmp_path)

    assert not report.warnings
    assert len(report.errors) == 1
    finding = report.errors[0]
    assert finding.check == "direct_contradiction"
    assert "policy-a" in finding.message
    assert "policy-b" in finding.message
    assert f"line {_line_of(text, 'policy-a')}" in finding.message
    assert f"line {_line_of(text, 'policy-b')}" in finding.message


def test_modality_conflict_on_bare_opposing_verbs(tmp_path: Path) -> None:
    text = _index("- **policy-a**: block(assertion_deletion)\n- **policy-b**: prefer(assertion_deletion)\n")
    _write_index(tmp_path, text)

    report = _run(tmp_path)

    assert len(report.errors) == 1
    assert report.errors[0].check == "modality_conflict"


def test_scope_overlap_via_nested_verb_call(tmp_path: Path) -> None:
    """`agent_config(paths): never(hand_edit)` vs a policy permitting edits to one of those paths."""
    text = _index(
        "- **protect-agent-config**: agent_config(AGENTS.md|.claude/settings): never(hand_edit)\n"
        "- **allow-settings-edits**: require_approval(.claude/settings): hand_edit\n"
    )
    _write_index(tmp_path, text)

    report = _run(tmp_path)

    assert len(report.errors) == 1
    finding = report.errors[0]
    assert finding.check == "scope_overlap"
    assert ".claude/settings" in finding.message
    assert "protect-agent-config" in finding.message
    assert "allow-settings-edits" in finding.message


def test_same_verb_with_different_targets_is_not_a_conflict(tmp_path: Path) -> None:
    """`never(commit): secrets` and `never(commit): --no-verify` both extend the same
    forbidden-target list; that is additive, not contradictory. Real chock content hits
    exactly this shape (block-no-verify and code-safety both scope `never` to `commit`)."""
    text = _index("- **policy-a**: never(commit): secrets\n- **policy-b**: never(commit): --no-verify\n")
    _write_index(tmp_path, text)

    report = _run(tmp_path)

    assert not report.errors
    assert not report.warnings


def test_reviewed_override_suppresses_exactly_that_finding(tmp_path: Path) -> None:
    text = _index(
        "- **policy-a**: never(dead_code): delete  # chock: conflict-reviewed dead_code\n"
        "- **policy-b**: prefer(dead_code): keep\n"
        "- **policy-c**: never(hook_bypass): skip\n"
        "- **policy-d**: prefer(hook_bypass): skip\n"
    )
    _write_index(tmp_path, text)

    report = _run(tmp_path)

    assert len(report.errors) == 1
    assert "hook_bypass" in report.errors[0].message
    assert "dead_code" not in report.errors[0].message


def test_redundancy_is_a_warning_naming_token_cost(tmp_path: Path) -> None:
    text = _index(
        "- **policy-a**: never(hook_bypass): skip|circumvent\n- **policy-b**: never(hook_bypass): skip|circumvent\n"
    )
    _write_index(tmp_path, text)

    report = _run(tmp_path)

    assert not report.errors
    assert len(report.warnings) == 1
    finding = report.warnings[0]
    assert finding.check == "redundancy"
    assert "policy-a" in finding.message
    assert "policy-b" in finding.message
    assert "tokens" in finding.message
    assert "AMB-1" in finding.message


def test_redundancy_override_suppresses_exactly_that_finding(tmp_path: Path) -> None:
    text = _index(
        "- **policy-a**: never(hook_bypass): skip  # chock: conflict-reviewed hook_bypass\n"
        "- **policy-b**: never(hook_bypass): skip\n"
    )
    _write_index(tmp_path, text)

    report = _run(tmp_path)

    assert not report.errors
    assert not report.warnings


def test_a_single_policy_cannot_conflict_with_itself(tmp_path: Path) -> None:
    text = _index("- **policy-a**:\n  never(dead_code): delete\n  prefer(dead_code): keep\n")
    _write_index(tmp_path, text)

    report = _run(tmp_path)

    assert not report.errors
    assert not report.warnings


def test_missing_index_is_a_silent_no_op(tmp_path: Path) -> None:
    report = _run(tmp_path)
    assert not report.errors
    assert not report.warnings


def test_this_repos_own_compiled_index_is_conflict_free() -> None:
    """The real catalog is unrelated policies; running the check on it must not false-positive."""
    root = Path(__file__).resolve().parents[1]
    report = _run(root)
    assert not report.errors, report.errors


def test_end_to_end_through_the_real_compiler(tmp_path: Path) -> None:
    """Two real policy manifests, compiled by the real index pipeline, still produce a finding."""

    def _write_policy(policy_id: str, rule_text: str) -> None:
        policy_dir = tmp_path / ".agents" / "policies" / policy_id
        policy_dir.mkdir(parents=True)
        data = {
            "id": policy_id,
            "name": policy_id,
            "version": "0.1.0",
            "description": f"Description for {policy_id}.",
            "artifact": "rule",
            "enforcement": "advise",
            "provenance": {"author": "x", "license": "Apache-2.0", "trust_tier": "sandbox"},
            "rule": {"text": rule_text},
        }
        (policy_dir / "manifest.yaml").write_text(yaml.safe_dump(data), encoding="utf-8")

    _write_policy("policy-a", "never(dead_code): delete")
    _write_policy("policy-b", "prefer(dead_code): keep")

    entries, _warnings = build_entries(tmp_path)
    output = render_index(entries, 2000)
    index_path = tmp_path / ".agents" / "policies" / "INDEX.md"
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(output.main, encoding="utf-8")

    report = _run(tmp_path)

    assert len(report.errors) == 1
    assert report.errors[0].check == "direct_contradiction"


def test_conflicts_only_flag_from_the_cli(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    text = _index("- **policy-a**: never(dead_code): delete\n- **policy-b**: prefer(dead_code): keep\n")
    _write_index(tmp_path, text)

    rc = conflicts_main(["--repo", str(tmp_path)])

    assert rc == 1
    out = capsys.readouterr().out
    assert "direct_contradiction" in out


def test_no_model_call_static_scan() -> None:
    """The design's core claim: nothing in this path can call a model."""
    for module in (checks_conflicts, ambient_parser):
        source = Path(module.__file__).read_text(encoding="utf-8").lower()
        for forbidden in ("openai", "anthropic", "requests.", "httpx", "socket.", "\\bllm\\b"):
            assert forbidden.rstrip(".") not in source, f"{module.__name__} mentions {forbidden!r}"


def test_no_model_call_network_and_subprocess_are_never_invoked(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Belt-and-suspenders: patch the only ways this process could reach a model, then run
    the check for real. If it needed a model call, one of these would raise."""

    def _boom(*_args, **_kwargs):
        raise AssertionError("check_ambient_conflicts must never touch the network or a subprocess")

    monkeypatch.setattr(urllib.request, "urlopen", _boom)
    monkeypatch.setattr(subprocess, "run", _boom)
    monkeypatch.setattr(subprocess, "Popen", _boom)

    text = _index("- **policy-a**: never(dead_code): delete\n- **policy-b**: prefer(dead_code): keep\n")
    _write_index(tmp_path, text)

    report = _run(tmp_path)
    assert len(report.errors) == 1
