"""Repo-wide coding standards, mechanically enforced.

Rule: no reviewable file exceeds 300 lines — beyond that, humans cannot review a
change in isolation and regression scope balloons. Applies to source, docs,
specs, and data alike. Split files by activity instead of growing them.
"""

from pathlib import Path

MAX_LINES = 300

# Generated or third-party files where line count is not a review concern, plus the one file
# the budget's own remedy cannot apply to.
EXEMPT = {
    ".chock/registry.json",  # generated by `chock registry scan`
    # Generated by `chock sync`: one JSON block per policy x agent pair, so it grows with
    # the installed set (18 policies x 13 agents crossed 300 on 2026-08-16). Its reviewer
    # is `sync --check`, which verifies it byte-for-byte against a recompile -- a stronger
    # review than any human read -- and "split by activity" has no meaning for it.
    ".chock/coverage.json",
    "LICENSE",  # verbatim Apache-2.0 text
    # Generated by uv pip compile --generate-hashes (command in its header): two hash
    # lines per artifact across semgrep's full dependency tree. Its reviewer is
    # regeneration from semgrep.in, not a human read, so the split-by-activity remedy
    # does not apply.
    "requirements/semgrep.txt",
    # The remedy this budget assumes is "split by activity". The gate runner is the one file
    # where that is unavailable: it is vendored into adopter repos as ONE self-contained,
    # stdlib-only file, and splitting it breaks the guarantee that a consumer needs nothing on
    # the machine but a Python interpreter. Sitting exactly at the cap, every line the CI range
    # mode added had to be paid for by compressing an existing comment -- and the comments here
    # record the defects that produced the code (a cp1252 crash on a staged U+2190, fnmatch
    # normcasing refs on Windows). Losing that history to satisfy a budget with no other
    # remedy is the worse trade, so the file is exempt and reviewed whole.
    "src/chock/gate/runner.py",
    ".chock/bin/gate.py",  # the vendored copy of the file above
    # Same constraint as the gate runner, and the same remedy-less budget: the PreToolUse
    # adapter is copied VERBATIM into every plugin package (claude, copilot, cursor, codex)
    # and vendored into adopter repos as one stdlib-only file, so "split by activity" would
    # break the promise that a consumer needs nothing but a Python interpreter -- and would
    # let four shipped packages disagree about how a payload is parsed. It crossed the cap
    # absorbing two silent fail-opens witnessed on a real Cursor install (a UTF-8 BOM
    # decoded through the platform locale, and Cursor ignoring exit 2 for plugin hooks);
    # those comments record why the code is shaped as it is.
    "src/chock/gate/pretooluse.py",
    ".chock/bin/pretooluse.py",  # the vendored copy of the file above
}

# Build output and tool caches are git-ignored artifacts, not reviewable source. Without
# these, running `pyinstaller packaging/chock.spec` locally makes this test fail on
# PyInstaller's own .toc/.html intermediates.
# Gitignored gate telemetry: grows without bound locally, never exists on a CI
# checkout -- so counting it made this test fail only on the machines that use the
# tool most. The compliance data files are verbatim enumerations of upstream
# frameworks (MITRE ATLAS ships 170 techniques); like LICENSE, their length is the
# publisher's, and "split by activity" has no meaning for a control list.
EXEMPT_PREFIXES = (".chock/log/", "src/chock/authoring/data/")

SKIP_DIRS = {
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    ".idea",
    ".claude",
    "node_modules",
    ".venv",
    "build",
    "dist",
}
SKIP_SUFFIXES = {".png", ".pyc"}
SKIP_DIR_SUFFIXES = (".egg-info",)


def test_no_file_exceeds_line_budget():
    repo_root = Path(__file__).resolve().parents[1]
    violations = []
    for path in repo_root.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(repo_root).as_posix()
        if set(path.parts) & SKIP_DIRS or path.suffix in SKIP_SUFFIXES or rel in EXEMPT:
            continue
        if rel.startswith(EXEMPT_PREFIXES):
            continue
        if any(part.endswith(SKIP_DIR_SUFFIXES) for part in path.parts):
            continue
        try:
            count = len(path.read_text(encoding="utf-8").splitlines())
        except (UnicodeDecodeError, OSError):
            continue
        if count > MAX_LINES:
            violations.append(f"{rel}: {count} lines")
    assert not violations, "Files exceed the 300-line review budget (split by activity):\n" + "\n".join(violations)
