"""Every __TOKEN__ placeholder in an emitted-artifact template is supplied by its
renderer, and every token a renderer replaces actually exists in the template --
no orphan and no dead placeholder (chock W48)."""

from __future__ import annotations

import re

from chock.compile.emitters import ci, git_hook, in_agent
from chock.gate import runtime_bundle
from chock.hooks import installers

_TOKEN_RE = re.compile(r"__[A-Z0-9_]+__")


def _assert_round_trips(template: str, values: dict[str, str]) -> str:
    """Every token literal must be present pre-render; none may survive post-render."""
    for token in values:
        assert token in template, f"renderer replaces {token!r} but it is absent from the template"
    found = set(_TOKEN_RE.findall(template))
    assert found == set(values), f"template tokens {found} do not match renderer tokens {set(values)}"
    rendered = template
    for token, value in values.items():
        rendered = rendered.replace(token, value)
    assert not _TOKEN_RE.search(rendered), f"orphan placeholder survived rendering: {rendered}"
    return rendered


def test_ci_step_template_tokens() -> None:
    rendered = _assert_round_trips(ci.STEP_TEMPLATE, {"__POLICY_ID__": "demo-policy", "__GATE_PATH__": "gate/path"})
    assert "demo-policy" in rendered
    assert "gate/path" in rendered


def test_git_hook_shim_template_tokens() -> None:
    rendered = _assert_round_trips(git_hook.SHIM_TEMPLATE, {"__POLICY_ID__": "demo-policy", "__EVENT__": "pre-push"})
    assert "demo-policy" in rendered
    assert "pre-push" in rendered


def test_in_agent_bash_template_tokens() -> None:
    rendered = _assert_round_trips(
        in_agent._BASH_TEMPLATE, {"__ADAPTER__": ".chock/bin/x.py", "__GUARD__": "impl/x.sh"}
    )
    assert ".chock/bin/x.py" in rendered
    assert "impl/x.sh" in rendered


def test_in_agent_powershell_template_tokens() -> None:
    rendered = _assert_round_trips(
        in_agent._POWERSHELL_TEMPLATE, {"__ADAPTER__": ".chock/bin/x.py", "__GUARD__": "impl/x.sh"}
    )
    assert ".chock/bin/x.py" in rendered
    assert "impl/x.sh" in rendered


def test_dispatcher_template_tokens() -> None:
    rendered = _assert_round_trips(
        installers.DISPATCHER_TEMPLATE, {"__EVENT__": "pre-commit", "__MARKER__": "# Generated by Chock"}
    )
    assert "pre-commit" in rendered


def test_validate_wrapper_windows_template_tokens() -> None:
    _assert_round_trips(
        installers._VALIDATE_WRAPPER_WINDOWS_TEMPLATE,
        {"__MARKER__": "# Generated by Chock", "__SCRIPT_NAME__": "99-chock-validate.ps1"},
    )


def test_policy_wrapper_template_tokens() -> None:
    _assert_round_trips(
        installers._POLICY_WRAPPER_TEMPLATE,
        {"__MARKER__": "# Generated by Chock", "__SOURCE_REL__": "policy/git-hook/git-pre-commit.sh"},
    )


def test_runtime_bundle_dispatch_template_token() -> None:
    assert runtime_bundle._DISPATCH_BRANCH_TOKEN in runtime_bundle._DISPATCH
    rendered_empty = runtime_bundle._DISPATCH.replace(runtime_bundle._DISPATCH_BRANCH_TOKEN, "")
    assert "__SESSION_START_BRANCH__" not in rendered_empty
    rendered_branch = runtime_bundle._DISPATCH.replace(
        runtime_bundle._DISPATCH_BRANCH_TOKEN, runtime_bundle._SESSION_START_BRANCH
    )
    assert "__SESSION_START_BRANCH__" not in rendered_branch
    assert "session_start" in rendered_branch


def test_static_templates_carry_no_orphan_tokens() -> None:
    """Templates with no placeholders at all must stay that way."""
    from chock.scaffold import agents_md, install_ci, templates

    for text in (
        install_ci.WORKFLOW_TEMPLATE,
        templates._GITATTRIBUTES_TEMPLATE,
        templates.POLICIES_GUARDRAIL,
        templates.SKILLS_GUARDRAIL,
        agents_md.POINTER_BLOCK,
        runtime_bundle._IMPORTS,
        runtime_bundle._SESSION_START_BRANCH,
        runtime_bundle._SESSION_START_ORCHESTRATION,
    ):
        assert not _TOKEN_RE.search(text), f"unexpected placeholder in static template: {text}"
