#!/usr/bin/env bash
# Generated by Chock. Best-effort guard against destructive commands.
# Not a security boundary; bypasses are possible via aliases, quoting, or non-standard paths.
set -eu

is_dangerous_target() {
    local t="$1"
    [[ "$t" == "/" || "$t" == "~" || "$t" == "." || "$t" == ".." || "$t" == /* || "$t" == ~/* ]]
}

# Flatten arguments for membership checks.
all_args=("$@")
flags=()
targets=()
subcommand=""

for arg in "$@"; do
    if [[ "$arg" =~ ^- ]]; then
        if [[ "$arg" =~ ^-- ]]; then
            flags+=("$arg")
        else
            # Expand combined short flags, e.g. -rf -> -r -f.
            for ((i=1; i<${#arg}; i++)); do
                flags+=("-${arg:i:1}")
            done
        fi
    else
        case "$arg" in
            git|rm|kubectl|terraform) ;;
            push|reset|clean|delete|destroy|checkout)
                if [[ -z "$subcommand" ]]; then subcommand="$arg"; fi
                ;;
            *) targets+=("$arg") ;;
        esac
    fi
done

has_flag() {
    local needle="$1"
    for f in "${flags[@]}"; do
        [[ "$f" == "$needle" ]] && return 0
    done
    return 1
}

has_command() {
    local cmd="$1"
    for a in "${all_args[@]}"; do
        [[ "$a" == "$cmd" ]] && return 0
    done
    return 1
}

# rm -rf /, rm -fr /var, rm -r -f /, etc.
if has_command "rm"; then
    if has_flag "-r" || has_flag "--recursive"; then
        if has_flag "-f" || has_flag "--force"; then
            for t in "${targets[@]}"; do
                if is_dangerous_target "$t"; then
                    echo "BLOCKED: destructive rm command targeting '$t' is not allowed without approval." >&2
                    exit 1
                fi
            done
        fi
    fi
fi

# git subcommands
if has_command "git"; then
    if [[ "$subcommand" == "push" ]]; then
        if has_flag "-f" || has_flag "--force"; then
            echo "BLOCKED: git push --force is not allowed; use --force-with-lease on a feature branch." >&2
            exit 1
        fi
    elif [[ "$subcommand" == "reset" ]]; then
        if has_flag "--hard"; then
            echo "BLOCKED: git reset --hard is not allowed without approval." >&2
            exit 1
        fi
    elif [[ "$subcommand" == "clean" ]]; then
        if has_flag "-f" || has_flag "--force"; then
            echo "BLOCKED: git clean -f is not allowed without approval." >&2
            exit 1
        fi
    elif [[ "$subcommand" == "checkout" ]]; then
        for t in "${targets[@]}"; do
            if [[ "$t" == "." ]]; then
                echo "BLOCKED: git checkout . is not allowed without approval." >&2
                exit 1
            fi
        done
    fi
fi

# kubectl delete
if has_command "kubectl" && [[ "$subcommand" == "delete" ]]; then
    echo "BLOCKED: kubectl delete is not allowed without approval." >&2
    exit 1
fi

# terraform destroy
if has_command "terraform" && [[ "$subcommand" == "destroy" ]]; then
    echo "BLOCKED: terraform destroy is not allowed without approval." >&2
    exit 1
fi

exit 0
