#!/usr/bin/env python3
"""Install a GitHub Actions workflow that runs the compiled ci-gate surface."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from chock.emit import write_generated

MARKER = "# Auto-generated by chock sync --ci. Re-run to refresh; edits are overwritten."

WORKFLOW_TEMPLATE = (
    MARKER
    + """
name: chock

on:
  pull_request:

jobs:
  chock-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Full history: `--event ci` diffs base...head, which needs the base ref present.
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # From git, not PyPI: chock is not published yet, so emitting
      # `pip install chock` would have failed on the adopter's first CI run --
      # an installer whose output does not run is worse than no installer.
      # Swap this for `pip install chock` once the package is on PyPI.
      - name: Install chock
        run: |
          python -m pip install --upgrade pip
          python -m pip install "git+https://github.com/open-coder-ai/chock"

      - name: Validate artifacts
        run: chock check

      - name: Compiled artifacts match their manifests
        run: chock sync --repo . --check

      - name: Run compiled CI gates (commit-range mode)
        run: |
          shopt -s nullglob
          status=0
          for gate in .chock/compiled/*/ci-gate/gate.json; do
            id="$(basename "$(dirname "$(dirname "$gate")")")"
            echo "::group::chock ci-gate: $id"
            python3 .chock/bin/gate.py run --gate "$gate" --event ci \\
              --base "origin/$GITHUB_BASE_REF" --head-ref "$GITHUB_HEAD_REF" || status=1
            echo "::endgroup::"
          done
          exit "$status"
"""
)


DEFAULT_PATH = ".github/workflows/chock.yml"


def ci_workflow_installed(repo_root: Path, path: str = DEFAULT_PATH) -> bool:
    """True when this repo's copy of the workflow at `path` is ours, not merely present."""
    dest = Path(repo_root) / path
    if not dest.exists():
        return False
    try:
        return MARKER in dest.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Install the Chock CI gate workflow")
    parser.add_argument("repo_root", nargs="?", default=".", help="Repository root (default: .)")
    parser.add_argument(
        "--path", default=".github/workflows/chock.yml", help="Workflow file to write, relative to repo_root"
    )
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()
    dest = repo_root / args.path

    if dest.exists():
        existing = dest.read_text(encoding="utf-8", errors="replace")
        if MARKER not in existing:
            print(
                f"[ERROR] {dest} already exists and was not written by chock. "
                "Remove it or pass --path to choose a different file.",
                file=sys.stderr,
            )
            return 1
        if existing == WORKFLOW_TEMPLATE:
            print(f"{dest} is already up to date")
            return 0

    dest.parent.mkdir(parents=True, exist_ok=True)
    write_generated(dest, WORKFLOW_TEMPLATE)
    print(f"Installed CI workflow at {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
