#!/usr/bin/env bash
# Generated by Chock hook installer.
hook_dir="$(cd "$(dirname "$0")" && pwd)"
script="$hook_dir/__PS1_NAME__"
if command -v cygpath >/dev/null 2>&1; then script="$(cygpath -w "$script")"; fi
powershell.exe -ExecutionPolicy Bypass -File "$script" "$@"
