"""Emit a CI gate step that re-runs the policy guard over a PR's commit range.

The old emitter's push step was `echo '<fake refs>' | bash git-pre-push.sh || true` --
hardcoded refs and `|| true`, so it could never fail. Its commit step ran
`git-pre-commit.sh`, which gates `git diff --cached`; a CI checkout has no staged index, so
it scanned nothing and always passed. Neither step could ever enforce anything -- the
surface was demoted to reflect that. This emitter instead invokes the vendored runner in
`--event ci` mode, which diffs the PR's real base...head range, so a violation exits
non-zero and actually fails the CI job.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from chock.compile.emitters.advisory import repo_root_from_output, template_message
from chock.emit import write_generated, write_generated_json
from chock.gate.build import build_gate_json, vendor_runner

STEP_TEMPLATE = """# Auto-generated by chock compile.
# Policy: {policy_id}
- name: chock-ci-gate ({policy_id})
  run: |
    PY=""
    for c in python3 python py; do
      if command -v "$c" >/dev/null 2>&1 && "$c" -c 'import tomllib' >/dev/null 2>&1; then PY="$c"; break; fi
    done
    [ -n "$PY" ] || {{ echo "gate: no python >= 3.11 (with tomllib) found on PATH" >&2; exit 2; }}
    base="${{GITHUB_BASE_REF:?ci-gate needs GITHUB_BASE_REF -- run this step on the pull_request event}}"
    "$PY" .chock/bin/gate.py run --gate {gate_path} --event ci --base "origin/$base" \\
      --head-ref "${{GITHUB_HEAD_REF:-}}"
"""


def emit(policy_dir: Path, output_dir: Path, manifest: dict[str, Any]) -> list[Path]:
    """Write a resolved gate.json plus a runnable CI step for it.

    The gate is built from the manifest via `build_gate_json`, the same source git-hook
    itself compiles from -- not by reading git-hook's compiled output off disk. Depending on
    git-hook having run first used to mean ci-gate silently produced nothing when compiled
    alone or reached first, invisibly, because nothing failed.
    """
    policy_dir = Path(policy_dir).resolve()
    output_dir = Path(output_dir).resolve()
    policy_id = manifest.get("id") or policy_dir.name
    repo_root = repo_root_from_output(output_dir)

    spec = build_gate_json(policy_dir, repo_root)
    # Only a gate that declares `commit` has a CI meaning (see runner.py's `run()`): a
    # `push`-only gate polices the act of pushing to a ref, which CI has no equivalent of.
    if spec is None or "commit" not in spec.get("on", []):
        return []
    spec["message"] = template_message(spec["message"], spec["params"])

    gate_json = output_dir / "gate.json"
    write_generated_json(gate_json, spec)

    # `<artifact_root>/bin/gate.py`, derived from the output tree exactly as git_hook does.
    # `vendor_runner` takes the `.chock` directory that owns the output, NOT a repo
    # root: passing `repo_root` here wrote the runner to `<repo>/bin/gate.py`, so the step
    # below pointed at a path that did not exist. The emitted step executes this file, so
    # ci-gate vendors it rather than relying on git_hook having run first.
    emitted = [gate_json, vendor_runner(output_dir.parents[2])]

    gate_path = f".chock/compiled/{policy_id}/ci-gate/gate.json"
    step = output_dir / "step.yaml"
    write_generated(step, STEP_TEMPLATE.format(policy_id=policy_id, gate_path=gate_path))
    emitted.append(step)
    return emitted
