"""Emit git-hook event entrypoints from a policy's implementations directory."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from chock.compile.emitters.advisory import repo_root_from_output, template_message
from chock.emit import write_generated, write_generated_json
from chock.gate.build import build_gate_json, vendor_runner

SHIM_TEMPLATE = """#!/usr/bin/env bash
# Auto-generated by chock compile. Declarative gate: {policy_id}
set -eu
repo_root="$(git rev-parse --show-toplevel)"
PY=""
for c in python3 python py; do
  if command -v "$c" >/dev/null 2>&1 && "$c" -c 'import tomllib' >/dev/null 2>&1; then PY="$c"; break; fi
done
[ -n "$PY" ] || {{ echo "gate: no python >= 3.11 (with tomllib) found on PATH" >&2; exit 2; }}
exec "$PY" "$repo_root/.chock/bin/gate.py" run \\
  --gate "$repo_root/.chock/compiled/{policy_id}/git-hook/gate.json" --event {event}
"""


def _emit_shims(output_dir: Path, policy_id: str, events: list[str]) -> list[Path]:
    emitted: list[Path] = []
    for event in events:
        if event == "commit":
            script_name = "git-pre-commit.sh"
            event_arg = "pre-commit"
        elif event == "push":
            script_name = "git-pre-push.sh"
            event_arg = "pre-push"
        else:
            continue
        shim = output_dir / script_name
        write_generated(shim, SHIM_TEMPLATE.format(policy_id=policy_id, event=event_arg))
        try:
            shim.chmod(0o755)
        except OSError:
            pass  # best-effort: chmod is a no-op/denied on Windows; the bash shim still runs via `bash <path>`
        emitted.append(shim)
    return emitted


def emit(policy_dir: Path, output_dir: Path, manifest: dict[str, Any]) -> list[Path]:
    """Emit git hooks from the manifest hook.gate as gate.json + shims."""
    policy_dir = Path(policy_dir).resolve()
    output_dir = Path(output_dir).resolve()
    policy_id = manifest.get("id") or policy_dir.name

    repo_root = repo_root_from_output(output_dir)
    spec = build_gate_json(policy_dir, repo_root)
    if spec is None:
        return []

    # Only a gate that fires at commit or push is a git-hook. A gate declaring, say, only
    # `tool_use` produces no shim, yet emitting gate.json + the runner still returned a
    # non-empty artifact list -- so coverage credited the policy `enforced-at-commit` with
    # nothing installed at commit time. Mirror ci-gate: no relevant event, no surface.
    hook_events = [e for e in spec.get("on", []) if e in ("commit", "push")]
    if not hook_events:
        return []

    # The block message the agent actually sees must name the params the gate actually
    # enforces. Authored as "(main/master)", it kept saying that after config resolution
    # changed the protected set -- so the gate blocked `production` while its own message
    # denied that `production` was protected.
    spec["message"] = template_message(spec["message"], spec["params"])

    gate_json = output_dir / "gate.json"
    write_generated_json(gate_json, spec)
    emitted: list[Path] = [gate_json]

    # `<artifact_root>/bin/gate.py`, derived from the output tree rather than the repo:
    # output_dir is `<artifact_root>/compiled/<policy_id>/git-hook`. Compiling into a temp
    # tree must vendor into that tree, not into the working repo -- see vendor_runner.
    # The runner is part of compiled output, so `recompile --check` compares it like any
    # other artifact, which is what makes tampering with it visible.
    emitted.append(vendor_runner(output_dir.parents[2]))
    emitted.extend(_emit_shims(output_dir, policy_id, hook_events))
    return emitted
