#!/usr/bin/env bash
# Auto-generated by chock compile. Script-backed gate: __POLICY_ID__
# The guard reads the change itself from git; its exit code is the verdict: 0 allows, 3 asks and
# 4 warns (both settled by the gate runner), anything else refuses. Only commit-msg passes an
# argument (the message file's path).
set -eu
repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"
guard="$repo_root/__GUARD_REL__"
if [ ! -f "$guard" ]; then
  echo "gate: __POLICY_ID__ ships no guard at __GUARD_REL__" >&2
  exit 2
fi
PY=""
for c in python3 python py; do
  if command -v "$c" >/dev/null 2>&1 && "$c" -c 'import tomllib' >/dev/null 2>&1; then PY="$c"; break; fi
done
case "$guard" in
  *.py)
    [ -n "$PY" ] || { echo "gate: no python >= 3.11 (with tomllib) found on PATH" >&2; exit 2; }
    rc=0
    "$PY" "$guard"__ARGV__ || rc=$?
    ;;
  *)
    command -v bash >/dev/null 2>&1 || { echo "gate: no bash found on PATH" >&2; exit 2; }
    rc=0
    bash "$guard"__ARGV__ || rc=$?
    ;;
esac
case "$rc" in
  3|4)
    [ -n "$PY" ] || { echo "gate: __POLICY_ID__ asked or warned, and no python >= 3.11 (with tomllib) is on PATH to settle it" >&2; exit 1; }
    exec "$PY" "$repo_root/.chock/bin/gate.py" script-verdict --policy __POLICY_ID__ --event __EVENT__ --exit "$rc"
    ;;
  *) exit "$rc" ;;
esac
