#!/usr/bin/env bash
# Auto-generated by chock compile. Script-backed gate: __POLICY_ID__
# The guard reads the change itself from git; it takes no arguments and its exit
# code is the verdict: 0 allows, anything else refuses.
set -eu
repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"
guard="$repo_root/__GUARD_REL__"
if [ ! -f "$guard" ]; then
  echo "gate: __POLICY_ID__ ships no guard at __GUARD_REL__" >&2
  exit 2
fi
case "$guard" in
  *.py)
    PY=""
    for c in python3 python py; do
      if command -v "$c" >/dev/null 2>&1 && "$c" -c 'import tomllib' >/dev/null 2>&1; then PY="$c"; break; fi
    done
    [ -n "$PY" ] || { echo "gate: no python >= 3.11 (with tomllib) found on PATH" >&2; exit 2; }
    exec "$PY" "$guard"
    ;;
  *)
    command -v bash >/dev/null 2>&1 || { echo "gate: no bash found on PATH" >&2; exit 2; }
    exec bash "$guard"
    ;;
esac
