"""Render INDEX.md and INDEX-extended.md from IndexEntry objects."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from chock.index.builder import IndexEntry

_HEADER = "<!-- GENERATED by `chock sync` — do not edit -->"
_TITLE = "# .agents/policies/INDEX.md"


def _token_estimate(text: str) -> int:
    """Deterministic, transparent estimator: characters / 4."""
    return max(0, len(text) // 4)


def _rule_lines(entry: IndexEntry) -> list[str]:
    """Render a rule, preserving its line structure.

    Rules are capped at ~2 lines by design and each line is an independent directive.
    Joining them with a space runs two directives together -- "... lint_clean
    never(fix_test_by): ..." reads as one malformed statement -- which destroys the
    structure the cap exists to create. Single-line rules keep the compact inline form;
    multi-line rules use a markdown list continuation.
    """
    body = [line.strip() for line in entry.rule_text.strip().splitlines() if line.strip()]
    if not body:
        return [f"- **{entry.id}**: (no rule text)"]
    if len(body) == 1:
        return [f"- **{entry.id}**: {body[0]}"]
    return [f"- **{entry.id}**:", *(f"  {line}" for line in body)]


def _gate_line(entry: IndexEntry) -> str:
    return f"- **{entry.id}**: {entry.description or 'automatic gate'}"


def _skill_line(entry: IndexEntry) -> str:
    return f"- **{entry.id}** — {entry.description or 'no description'}\n  → `{entry.manifest_path}`"


def _render_main(entries: list[IndexEntry], has_extended: bool) -> str:
    lines: list[str] = [_HEADER, "", _TITLE, ""]
    sections: dict[str, list[str]] = {"rule": [], "hook": [], "skill": []}

    for entry in entries:
        if entry.artifact == "rule":
            sections["rule"].extend(_rule_lines(entry))
        elif entry.artifact == "hook":
            sections["hook"].append(_gate_line(entry))
        else:
            sections["skill"].append(_skill_line(entry))

    if sections["rule"]:
        lines.extend(["## Rules — always apply", ""] + sections["rule"] + [""])
    if sections["hook"]:
        lines.extend(["## Gates — enforced automatically at commit/push", ""] + sections["hook"] + [""])
    if sections["skill"]:
        lines.extend(["## Skills — invoke when the task matches", ""] + sections["skill"] + [""])

    if has_extended:
        lines.append("Additional advise-tier policies are in `.agents/policies/INDEX-extended.md`.")

    return "\n".join(lines).rstrip() + "\n"


def _render_extended(entries: list[IndexEntry]) -> str:
    lines: list[str] = [
        "<!-- GENERATED by `chock sync` — do not edit -->",
        "",
        "# .agents/policies/INDEX-extended.md",
        "",
        "These advise-tier policies were demoted from the main index to keep the attention",
        "budget focused on block and verify enforcement. Read them when the task matches.",
        "",
    ]
    for entry in entries:
        if entry.artifact == "rule":
            lines.extend(_rule_lines(entry) + [""])
        elif entry.artifact == "hook":
            lines.append(_gate_line(entry) + "\n")
        else:
            lines.append(_skill_line(entry) + "\n")
    return "\n".join(lines).rstrip() + "\n"


@dataclass
class IndexOutput:
    main: str
    extended: str | None
    main_tokens: int
    extended_tokens: int
    max_tokens: int
    warning: str | None


def render_index(entries: Iterable[IndexEntry], max_tokens: int) -> IndexOutput:
    """Split entries by budget and render main + optional extended files."""
    sorted_entries = sorted(entries, key=lambda e: e.sort_key())
    demoted: set[str] = set()
    extended_ids: list[str] = []
    main: list[IndexEntry] = []

    while True:
        main = [e for e in sorted_entries if e.id not in demoted]
        has_extended = bool(demoted)
        text = _render_main(main, has_extended)
        tokens = _token_estimate(text)
        if tokens <= max_tokens:
            break
        # Remove the last advise-tier entry (by sorted order) to protect block/verify.
        moved = False
        for entry in reversed(sorted_entries):
            if entry.enforcement == "advise" and entry.id not in demoted:
                demoted.add(entry.id)
                extended_ids.append(entry.id)
                moved = True
                break
        if not moved:
            break

    main = [e for e in sorted_entries if e.id not in demoted]
    main_text = _render_main(main, bool(demoted))
    main_tokens = _token_estimate(main_text)

    extended_text: str | None = None
    extended_tokens = 0
    if demoted:
        extended = [e for e in sorted_entries if e.id in demoted]
        extended_text = _render_extended(extended)
        extended_tokens = _token_estimate(extended_text)

    warning: str | None = None
    if main_tokens > max_tokens:
        warning = f"INDEX overflow: ~{main_tokens} tokens (budget {max_tokens}); block/verify entries do not fit."
    elif main_tokens >= int(max_tokens * 0.8):
        warning = f"INDEX is at {main_tokens}/{max_tokens} tokens ({main_tokens * 100 // max_tokens}% of budget)."

    return IndexOutput(
        main=main_text,
        extended=extended_text,
        main_tokens=main_tokens,
        extended_tokens=extended_tokens,
        max_tokens=max_tokens,
        warning=warning,
    )
