"""Deciding which git hook files Chock wrote, and moving foreign ones aside.

Split out of `install.py` because it is a different activity from installing: installation
writes files, this decides whose they are. The distinction is load-bearing enough to review on
its own, since getting it wrong in one direction destroys work an adopter did.
"""

from __future__ import annotations

import shutil
from pathlib import Path

#: The only thing distinguishing a hook this installer wrote from one the adopter wrote.
#: Substituted into `install.DISPATCHER_TEMPLATE` rather than duplicated in it, so the string
#: the installer writes and the string it looks for cannot drift apart.
GENERATED_MARKER = "# Generated by Chock hook installer."

#: Where a foreign hook is moved so the dispatcher can still chain to it. `00-` keeps it first
#: in the glob order, ahead of anything Chock registers.
RELOCATED_NAME = "00-preexisting"


def is_ours(path: Path) -> bool:
    """True only when this installer is certain it wrote `path`.

    Certainty is the point, and the asymmetry is deliberate. A false positive means a hook the
    adopter wrote is not relocated, and `install_dispatcher` then overwrites it -- their work
    is gone, with no copy anywhere. A false negative means our own dispatcher is relocated to
    `00-preexisting`, which is the inert wart this exists to avoid: untidy, harmless, and
    cleaned up on the next run.

    So an unreadable or undecodable file answers False and is preserved.
    """
    try:
        return GENERATED_MARKER in path.read_text(encoding="utf-8", errors="strict")
    except (OSError, UnicodeDecodeError):
        return False


def relocate_existing_hook(path: Path, impl_dir: Path) -> None:
    """Move a pre-existing foreign hook aside so the dispatcher can chain to it."""
    if not path.exists():
        return

    # Re-running the documented quickstart -- `init` then `install-hooks` -- used to relocate
    # Chock's own dispatcher into `pre-commit.d/00-preexisting`, treating it as foreign.
    # The copy is inert: it globs `$HOOK_DIR/pre-commit.d/` resolved from its own location
    # inside `pre-commit.d/`, so it looks for a nested directory that does not exist. Harmless,
    # but every adopter following the quickstart got one, and it reached the catalog's README
    # transcript -- a tool that looks confused about its own output invites doubt about the
    # parts that are not cosmetic.
    if is_ours(path):
        return

    # A second foreign hook (husky reinstalled between syncs, say) must not overwrite the
    # first relocation -- copy2 onto an existing 00-preexisting silently destroyed the
    # original this function had promised to chain to. Identical content is a no-op;
    # different content gets the next free numbered slot, still ahead of Chock's wrappers.
    relocated = impl_dir / RELOCATED_NAME
    n = 2
    while relocated.exists() and relocated.read_bytes() != path.read_bytes():
        relocated = impl_dir / f"{RELOCATED_NAME}-{n}"
        n += 1
    if not relocated.exists():
        shutil.copy2(path, relocated)
    path.unlink()
    relocated.chmod(0o755)
    print(f"Relocated existing {path.name} to {impl_dir.name}/{relocated.name}")


def remove_self_relocated_hook(impl_dir: Path) -> None:
    """Delete a `00-preexisting` that is a copy of our own dispatcher.

    Repairs repos already carrying the artefact rather than only preventing new ones -- the bug
    shipped, and an adopter has no reason to know the file is inert. Guarded on the marker, so
    only a file this installer demonstrably wrote is removed; a genuine relocated hook survives
    every subsequent install, which it must, or the installer would eventually eat the hook it
    promised to chain to.
    """
    relocated = impl_dir / RELOCATED_NAME
    if relocated.exists() and is_ours(relocated):
        relocated.unlink()
        print(f"Removed {impl_dir.name}/{RELOCATED_NAME} (a stale copy of our own dispatcher)")
