"""Deciding which git hook files Chock wrote, and moving foreign ones aside."""

from __future__ import annotations

import shutil
from pathlib import Path

GENERATED_MARKER = "# Generated by Chock hook installer."

RELOCATED_NAME = "00-preexisting"


def is_ours(path: Path) -> bool:
    """True only when this installer is certain it wrote `path`."""
    try:
        return GENERATED_MARKER in path.read_text(encoding="utf-8", errors="strict")
    except (OSError, UnicodeDecodeError):
        return False


def relocate_existing_hook(path: Path, impl_dir: Path) -> None:
    """Move a pre-existing foreign hook aside so the dispatcher can chain to it."""
    if not path.exists():
        return

    if is_ours(path):
        return

    relocated = impl_dir / RELOCATED_NAME
    n = 2
    while relocated.exists() and relocated.read_bytes() != path.read_bytes():
        relocated = impl_dir / f"{RELOCATED_NAME}-{n}"
        n += 1
    if not relocated.exists():
        shutil.copy2(path, relocated)
    path.unlink()
    relocated.chmod(0o755)
    print(f"Relocated existing {path.name} to {impl_dir.name}/{relocated.name}")


def remove_self_relocated_hook(impl_dir: Path) -> None:
    """Delete a `00-preexisting` that is a copy of our own dispatcher."""
    relocated = impl_dir / RELOCATED_NAME
    if relocated.exists() and is_ours(relocated):
        relocated.unlink()
        print(f"Removed {impl_dir.name}/{RELOCATED_NAME} (a stale copy of our own dispatcher)")
