"""The gate runner: stdlib-only; `chock.gate.assemble` builds the vendored single-file gate.py from it."""

from __future__ import annotations

from .actor import agent_commit, agent_signal, allowed_ids, committed_rollout, rollout, rollout_from_text, rollout_level
from .cli import main
from .constants import (
    _EVENT_NAME,
    _LOG_MATCH_CAP,
    _LOG_MAX_BYTES,
    ACTION_ASK,
    ACTION_BLOCK,
    ACTION_WARN,
    AGENT_COMMIT_ENV,
    AGENT_COMMIT_EVENT,
    AGENT_EVENTS,
    AI_AGENT_ENV,
    ALLOW_ENV,
    CLAUDECODE_ENV,
    COMPILED_PREFIX,
    CONFIG_AGENT_ENV_KEY,
    EXIT_ASK,
    EXIT_WARN,
    GATE_LOG_ENV,
    HEAD_WAIVER_EVENTS,
    POLICIES_PREFIX,
    ROLLOUT_ASK,
    ROLLOUT_ENFORCE,
    ROLLOUT_ENV,
    ROLLOUT_OBSERVE,
    ROLLOUT_RANK,
    SCRIPT_BASE_GATE,
    STOP_EVENT,
    TOOL_USE_EVENT,
    VERDICT_ERROR,
    WAIVABLE_EVENTS,
    WRITE_PATH_KINDS,
)
from .context import GateContext, GateResult, WriteContext
from .kinds import EXTRACTORS, KINDS
from .material import own_paths
from .report import _annotation, _cell, _encodable, _reason, _repo_relative, ci_inert
from .verdict import Evaluation, _policy_id, _verdict, evaluate, judge, run, script_verdict

__all__ = [
    "ACTION_ASK",
    "ACTION_BLOCK",
    "ACTION_WARN",
    "AGENT_COMMIT_ENV",
    "AGENT_COMMIT_EVENT",
    "AGENT_EVENTS",
    "AI_AGENT_ENV",
    "ALLOW_ENV",
    "CLAUDECODE_ENV",
    "COMPILED_PREFIX",
    "CONFIG_AGENT_ENV_KEY",
    "EXIT_ASK",
    "EXIT_WARN",
    "EXTRACTORS",
    "GATE_LOG_ENV",
    "HEAD_WAIVER_EVENTS",
    "KINDS",
    "POLICIES_PREFIX",
    "ROLLOUT_ASK",
    "ROLLOUT_ENFORCE",
    "ROLLOUT_ENV",
    "ROLLOUT_OBSERVE",
    "ROLLOUT_RANK",
    "SCRIPT_BASE_GATE",
    "STOP_EVENT",
    "TOOL_USE_EVENT",
    "VERDICT_ERROR",
    "WAIVABLE_EVENTS",
    "WRITE_PATH_KINDS",
    "_EVENT_NAME",
    "_LOG_MATCH_CAP",
    "_LOG_MAX_BYTES",
    "Evaluation",
    "GateContext",
    "GateResult",
    "WriteContext",
    "_annotation",
    "_cell",
    "_encodable",
    "_policy_id",
    "_reason",
    "_repo_relative",
    "_verdict",
    "agent_commit",
    "agent_signal",
    "allowed_ids",
    "ci_inert",
    "committed_rollout",
    "evaluate",
    "judge",
    "main",
    "own_paths",
    "rollout",
    "rollout_from_text",
    "rollout_level",
    "run",
    "script_verdict",
]
